framework:
    rate_limiter:
        register:
            policy: 'sliding_window'
            limit: 10
            interval: '1 hour'
        forgot_password:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour'
        apply:
            policy: 'sliding_window'
            limit: 10
            interval: '1 hour'
        message:
            policy: 'sliding_window'
            limit: 60
            interval: '1 hour'
        public_campaign:
            policy: 'sliding_window'
            limit: 60
            interval: '1 minute'
